# -*- coding: utf-8 -*-
"""LXSEQ 샘플 데이터 — Maroon 5 / Sugar (LX-SEQ v1.1)"""

BAR = 2.0  # 120BPM 4/4 → 1마디 2.000초
RUNTIME = 236.0


def tc(sec):
    if sec is None:
        return ""
    m, s = divmod(round(sec, 1), 60)
    return "%02d:%04.1f" % (int(m), s)


HEAD_META = [
    ("SONG_TITLE", "Sugar"),
    ("ARTIST", "Maroon 5"),
    ("RUNTIME", "03:56.0"),
    ("BPM", "120 (고정)"),
    ("TIME_SIG", "4/4"),
    ("KEY", "D♭ major"),
    ("VENUE", "확인필요"),
    ("SHOW_DATE", "확인필요"),
    ("CONSOLE", "grandMA3"),
    ("TC_SOURCE", "LTC"),
    ("TC_ORIGIN", "00:00.0 = 곡 첫 음(신스 스탭 1박). 카운트인 없음."),
    ("SPEC_VER", "LX-SEQ v2.1"),
    ("RIG_REF", "LXSEQ_RIG_01 r3 — 패치·그룹·프리셋·FX·콘솔 설정은 RIG 팩 참조"),
    (
        "REV_NOTE",
        "v1.0 검증 FAIL→v1.1 개정, v2.0에서 실행 레이어(PATCH·PRESET·CUE-EX) 추가. r3: lighting-designer 플러그인 파이프라인 재생성판 (2026-08-21, 러닝타임·BPM 웹 재검증 완료).",
    ),
    ("AUTHOR", "Claude / lighting-designer 플러그인 파이프라인"),
    ("REV", "r3"),
    ("TC_METHOD", "DERIVED — 마디연산(1마디=2.000s) 도출. 음원 청취 미검증. 리허설 LTC 대조 필수."),
]

FIXTURE_GROUPS = [
    ("FOH", "전면 페이스 라이트", "Profile ×8", "미사용(샘플)"),
    ("KEY", "주 인물광", "Profile ×6", "보컬 중심"),
    ("BACK", "백라이트 / 실루엣", "Wash ×12", "상시 사용"),
    ("SIDE-L", "사이드 붐 (하수)", "Wash ×6", ""),
    ("SIDE-R", "사이드 붐 (상수)", "Wash ×6", ""),
    ("WASH-U", "업스테이지 워시", "LED Par ×10", ""),
    ("WASH-D", "다운스테이지 워시", "LED Par ×10", ""),
    ("MOVER-U", "무빙 스팟 (업)", "Moving Spot ×8", "빔 연출 주력"),
    ("MOVER-D", "무빙 워시 (다운)", "Moving Wash ×8", ""),
    ("BLIND", "블라인더", "2-cell ×6", "객석 각도 주의"),
    ("STROBE", "스트로브", "LED Strobe ×4", "광과민 고지 대상"),
    ("LED-W", "LED 월 / 픽셀", "P3.9 백월", "영상팀 협의"),
    ("HAZE", "헤이저", "Hazer ×2", "곡 시작 30초 전 선투입"),
    ("FOLLOW-1", "팔로우스팟 1", "1.2kW", "미사용(샘플)"),
]

PALETTE = [
    ("P1", "골드 앰버", "~2400K / R255 G180 B60", "#FFB43C", "곡의 기본 온도 · 디스코 골드"),
    ("P2", "웜 화이트", "~3200K", "#FFE0B0", "보컬 인물 기본"),
    ("P3", "뉴트럴 화이트", "~5600K", "#F2F5F8", "예비 (샘플 미사용)"),
    ("P4", "핫 핑크", "R255 G60 B158", "#FF3C9E", "후렴 주색 · 화려함"),
    ("P5", "딥 퍼플", "R90 G43 B200", "#5A2BC8", "브리지 · 절제"),
    ("P6", "터쿼이즈", "R46 G216 B216", "#2ED8D8", "프리코러스 · 각성"),
    ("P7", "선셋 오렌지", "R255 G106 B40", "#FF6A28", "후렴 보조 · 확산"),
    ("P8", "블랙아웃", "—", "#101418", "암전"),
]

SECTIONS = [
    ("INTRO", 4, 0.0, 8.0),
    ("VERSE1", 16, 8.0, 40.0),
    ("PRE1", 8, 40.0, 56.0),
    ("CHORUS1", 16, 56.0, 88.0),
    ("VERSE2", 8, 88.0, 104.0),
    ("PRE2", 8, 104.0, 120.0),
    ("CHORUS2", 16, 120.0, 152.0),
    ("BRIDGE", 8, 152.0, 168.0),
    ("CHORUS3", 32, 168.0, 232.0),
    ("OUTRO", 2, 232.0, 236.0),
]

# Q# | Section | In | Out | Mood | Color | Intensity | Fixture | Movement | Effect | Transition | Fade | Note | (내부)peak
CUES = [
    (
        "Q010",
        "INTRO",
        0.0,
        8.0,
        "화사, 등장",
        "P1 골드앰버 / P2 웜화이트",
        "55",
        "BACK+WASH-U+HAZE",
        "STATIC",
        "NONE",
        "SNAP",
        "0.0",
        "[MANUAL] 헤이즈 곡 시작 30초 전 선투입 · 첫 박에 스냅 인",
        55,
        "#FFB43C",
    ),
    (
        "Q020",
        "VERSE1",
        8.0,
        24.0,
        "경쾌, 근접",
        "P2 웜화이트 / P1 골드앰버",
        "KEY 70 / BACK 35",
        "KEY+BACK",
        "STATIC",
        "NONE",
        "XFADE",
        "1.5",
        "보컬 인 · 페이스 확보 우선, 백라이트 낮게",
        70,
        "#FFE0B0",
    ),
    (
        "Q030",
        "VERSE1",
        24.0,
        40.0,
        "확장, 그루브",
        "P2 웜화이트 / P6 터쿼이즈",
        "KEY 70 / SIDE 40",
        "KEY+BACK+SIDE-L+SIDE-R",
        "STATIC",
        "PULSE @2bar",
        "XFADE",
        "2.0",
        "사이드 합류로 폭 확보 · 펄스는 2마디 주기 얕게",
        70,
        "#FFE0B0",
    ),
    (
        "Q040",
        "PRE1",
        40.0,
        56.0,
        "축적, 상승",
        "P6 터쿼이즈 / P5 딥퍼플",
        "60",
        "SIDE-L+SIDE-R+MOVER-U",
        "TILT-UP @slow",
        "BREATHE @1bar",
        "FADE",
        "8.0",
        "8초에 걸쳐 서서히 · 후렴 직전 60 도달",
        60,
        "#2ED8D8",
    ),
    (
        "Q050",
        "CHORUS1",
        56.0,
        72.0,
        "개방, 축제",
        "P4 핫핑크 / P1 골드앰버",
        "90",
        "MOVER-U+MOVER-D+BACK+WASH-D",
        "FAN-OUT @mid",
        "CHASE @1/8",
        "SNAP",
        "0.0",
        "후렴 첫 박 정확히 · 1차 웨이브 정점",
        90,
        "#FF3C9E",
    ),
    (
        "Q060",
        "CHORUS1",
        72.0,
        88.0,
        "유지, 회전",
        "P4 핫핑크 / P6 터쿼이즈",
        "90",
        "MOVER-U+MOVER-D+BACK",
        "CIRCLE @mid",
        "CHASE @1/8",
        "XFADE",
        "1.0",
        "강도 유지, 색만 교체 · 후렴 후반 지루함 방지",
        90,
        "#FF3C9E",
    ),
    (
        "Q070",
        "VERSE2",
        88.0,
        104.0,
        "하강, 근접",
        "P2 웜화이트 / P5 딥퍼플",
        "KEY 65 / BACK 30",
        "KEY+BACK",
        "STATIC",
        "NONE",
        "XFADE",
        "2.0",
        "2차 웨이브 시작 · V1보다 5 낮게 잡아 후속 상승폭 확보",
        65,
        "#FFE0B0",
    ),
    (
        "Q080",
        "PRE2",
        104.0,
        120.0,
        "축적, 압박",
        "P6 터쿼이즈 / P4 핫핑크",
        "70",
        "SIDE-L+SIDE-R+MOVER-U+LED-W",
        "TILT-UP @mid",
        "PULSE @1beat",
        "FADE",
        "8.0",
        "PRE1보다 10 높게 · LED월 합류 · 펄스 1박 주기로 조임",
        70,
        "#2ED8D8",
    ),
    (
        "Q090",
        "CHORUS2",
        120.0,
        136.0,
        "개방, 확산",
        "P4 핫핑크 / P7 선셋오렌지",
        "95",
        "MOVER-U+MOVER-D+BACK+WASH-D+LED-W",
        "FAN-OUT @fast",
        "CHASE @1/8",
        "SNAP",
        "0.0",
        "2차 웨이브 정점 · 1차보다 5 높게",
        95,
        "#FF3C9E",
    ),
    (
        "Q100",
        "CHORUS2",
        136.0,
        152.0,
        "유지, 확장",
        "P1 골드앰버 / P4 핫핑크",
        "95",
        "MOVER-U+MOVER-D+BACK+WASH-D+LED-W+BLIND",
        "SWEEP-H @fast",
        "CHASE @1/8",
        "XFADE",
        "1.0",
        "블라인더 합류 · 객석 직사 각도 리허설에서 확정",
        95,
        "#FFB43C",
    ),
    (
        "Q110",
        "BRIDGE",
        152.0,
        160.0,
        "절제, 집중",
        "P5 딥퍼플 / —",
        "35",
        "KEY+BACK",
        "STATIC",
        "NONE",
        "XFADE",
        "2.5",
        "급강하 · 3차 웨이브 lull 구간, 낙차 확보가 목적",
        35,
        "#5A2BC8",
    ),
    (
        "Q120",
        "BRIDGE",
        160.0,
        168.0,
        "재점화, 축적",
        "P5 딥퍼플 / P4 핫핑크",
        "75",
        "KEY+BACK+SIDE-L+SIDE-R",
        "TILT-UP @fast",
        "BREATHE @1bar",
        "FADE",
        "7.0",
        "마지막 후렴 직전까지 7초 상승 · 35→75",
        75,
        "#5A2BC8",
    ),
    (
        "Q130",
        "CHORUS3",
        168.0,
        184.0,
        "폭발, 최대",
        "P4 핫핑크 / P1 골드앰버",
        "100",
        "MOVER-U+MOVER-D+BACK+WASH-D+WASH-U+SIDE-L+SIDE-R+LED-W",
        "FAN-OUT @fast",
        "CHASE @1/8",
        "SNAP",
        "0.0",
        "곡 전체 최고점 · 가용 그룹 전개 (FOH 제외)",
        100,
        "#FF3C9E",
    ),
    (
        "Q140",
        "CHORUS3",
        184.0,
        200.0,
        "유지, 회전",
        "P7 선셋오렌지 / P6 터쿼이즈",
        "100",
        "MOVER-U+MOVER-D+BACK+WASH-D+WASH-U+SIDE-L+SIDE-R+LED-W",
        "CIRCLE @fast",
        "RAINBOW",
        "XFADE",
        "1.0",
        "더블 후렴 전반부 종료 · 색상만 순환시켜 체감 변화 유지",
        100,
        "#FF6A28",
    ),
    (
        "Q150",
        "CHORUS3",
        200.0,
        216.0,
        "최고조, 난반사",
        "P4 핫핑크 / P6 터쿼이즈",
        "100",
        "MOVER-U+MOVER-D+BACK+WASH-D+SIDE-L+SIDE-R+LED-W+BLIND+STROBE",
        "SWEEP-H @fast",
        "STROBE @2bar",
        "SNAP",
        "0.0",
        "스트로브 구간 · 광과민성 사전 고지 필수 · 2마디 주기로 제한",
        100,
        "#FF3C9E",
    ),
    (
        "Q160",
        "CHORUS3",
        216.0,
        232.0,
        "해소 준비",
        "P1 골드앰버 / P2 웜화이트",
        "85",
        "MOVER-U+MOVER-D+BACK+WASH-D",
        "CIRCLE @mid",
        "TWINKLE",
        "XFADE",
        "2.0",
        "스트로브 해제 · 색온도 회복하며 종료 준비",
        85,
        "#FFB43C",
    ),
    (
        "Q170",
        "OUTRO",
        232.0,
        236.0,
        "잔향, 종료",
        "P1 골드앰버 / —",
        "20",
        "BACK+WASH-U",
        "STATIC",
        "NONE",
        "FADE",
        "3.5",
        "마지막 음 위에서 하강 · 85→20",
        20,
        "#FFB43C",
    ),
    (
        "Q180",
        "OUTRO",
        236.0,
        None,
        "암전",
        "P8 블랙아웃 / —",
        "0",
        "ALL",
        "STATIC",
        "NONE",
        "FADE",
        "1.5",
        "[MANUAL] 곡 종료 확인 후 · 다음 곡 인계 시 BACK 15% 잔광 유지",
        0,
        "#101418",
    ),
]

NOTES = [
    (
        "확인필요",
        "전체",
        "마디맵이 마디연산(1마디=2.000s) 도출값. 음원 청취 미검증 — 픽업/하프바 삽입 시 전 구간 오프셋 발생. 리허설에서 LTC 대조 필수.",
        "2026-08-20",
        "미해결",
    ),
    (
        "확인필요",
        "전체",
        "VENUE·SHOW_DATE 미확정. CONSOLE은 grandMA3로 확정(r3), 콘솔 매핑은 console-transfer 산출물(ma3.txt·macros.xml) 참조.",
        "2026-08-21",
        "미해결",
    ),
    (
        "확인필요",
        "-",
        "HEAD 장비 그룹의 기종·대수는 표준 가정값. 실제 플롯 확정 후 교체 필요.",
        "2026-08-20",
        "미해결",
    ),
    (
        "확인필요",
        "Q100, Q150",
        "BLIND 객석 직사 각도 미확정. 리허설에서 최대 틸트각 확정 후 기입.",
        "2026-08-20",
        "미해결",
    ),
    (
        "장비이슈",
        "Q150",
        "STROBE @2bar 사용 — 광과민성 발작 고지 대상. 공연 안내/사이니지 확인 필요.",
        "2026-08-20",
        "미해결",
    ),
    (
        "장비이슈",
        "Q080, Q090, Q130",
        "LED-W 큐가 영상팀 콘텐츠와 충돌 가능. 영상 큐시트와 대조 필요.",
        "2026-08-20",
        "미해결",
    ),
    (
        "스펙개정후보",
        "-",
        "Section enum에 PRE 반복 표기 없음 → v1.1에서 PRE1~PRE3·VERSE3 추가. 검증 FAIL로 실제 검출된 항목.",
        "2026-08-20",
        "해결(v1.1)",
    ),
    (
        "스펙개정후보",
        "-",
        "더블 후렴(32마디)이 CHORUS3 하나로 묶임 → v1.1에서 CHORUS4 추가 및 분할/단일 선택 규칙 명문화. 이 시트는 단일 유지.",
        "2026-08-20",
        "해결(v1.1)",
    ),
    (
        "스펙개정후보",
        "-",
        "프리롤 표기 규칙 부재 → v1.1에서 PRE-ROLL 섹션 + 음수 TC 허용. 이 시트는 Q010 Note에 [MANUAL]로 유지.",
        "2026-08-20",
        "해결(v1.1)",
    ),
    (
        "스펙개정후보",
        "-",
        "전환 밀도 규칙 예외 조항 부재 → v1.1 §3.6.5에 종료 암전·PRE-ROLL·BUMP 예외 명문화 (Q170→Q180 간격 4.0s).",
        "2026-08-20",
        "해결(v1.1)",
    ),
    (
        "스펙개정후보",
        "-",
        "TC 검증 상태 필드 부재 → v1.1 §2.4에 TC_METHOD(VERIFIED/DERIVED) 필수 필드 신설.",
        "2026-08-20",
        "해결(v1.1)",
    ),
]
